List view
peter-phillips/Learn-By-Planning pull request #30
Opened 2021-05-28 04:23 UTC by jhbanh

Everything is working for the list view except for the coloring and maybe the styling.

2021-05-28 04:34 UTC, kmgarcia23 commented on frontend/src/IndividualTask.jsx
> +    <Card style={{
Good use of Cards for the tasks

2021-05-28 04:38 UTC, kmgarcia23 commented on frontend/src/List.jsx
> +    tasks.forEach((value, key) => comps.push(<TaskHolder Key={key} tasks={value} />));
Nice job breaking up your components to keep the code less complex.

2021-05-28 04:45 UTC, kmgarcia23 reviewed
LGTM!

2021-05-29 00:54 UTC, peter-phillips requested changes
Looks good except for catching backend errors

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/CreateForm.jsx
> +    else setUser({ name: user.name, email: value, password: user.password });
Seems rather redundant, if both password and name are are already stored in user

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/CreateNew.jsx
> +      return false;
Should catch 409 if user with email already exists

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/Form.jsx
> +    else setUser({ email: value, password: user.password });
Here as well doesnt user store both the name and password? I think this can be cleaned up

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/List.jsx
> +    } catch (error) {
Is only good if response is 201, 401 for unauthorized access. Should be fixed

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/Login.jsx
> +    } catch (error) {
Needs to be 200 if someone was logged out and and 304 if nothing was modified, Either needs to pass, anything else should fail

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/Login.jsx
> +      return false;
Needs to catch 403 for wrong username/password, anything else is a backend failure

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/Login.jsx
> +    } catch (error) {
Should also set your frontend auth to false

2021-05-29 00:54 UTC, peter-phillips commented on frontend/src/Today.jsx
> +        return true;
Needs to catch 401 for unauthorized access aka user logged out, should theoretically route back to login

2021-05-29 05:56 UTC, minadedijer commented
Looks good but could be a lot easier if you used FullCalendar, that way the Calendar and List View would look similar as well.

2021-05-31 04:18 UTC, merged